// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Attachment는 이메일 첨부파일을 나타낸다.
 */
export interface Attachment {
    /**
     * Name은 파일명.
     */
    "name": string;

    /**
     * Path는 전송 시 로컬 파일 경로.
     */
    "path"?: string;

    /**
     * Size는 바이트 단위 크기(수신 시).
     */
    "size"?: number;
}

/**
 * Message는 단일 이메일 메시지를 나타낸다.
 * IMAP 수신 결과와 SMTP 전송 입력 양쪽에서 재사용된다.
 */
export interface Message {
    /**
     * UID는 IMAP 메시지 식별자(수신 시에만 유효).
     */
    "uid"?: number;

    /**
     * From은 발신자 주소.
     */
    "from": string;

    /**
     * To는 수신자 주소 목록(콤마로 조인된 문자열).
     */
    "to": string;

    /**
     * Cc는 참조 주소 목록(콤마로 조인된 문자열).
     */
    "cc"?: string;

    /**
     * Subject는 메일 제목.
     */
    "subject": string;

    /**
     * Body는 메일 본문(plaintext).
     */
    "body": string;

    /**
     * Date는 RFC3339 포맷의 메일 날짜(수신 시).
     */
    "date"?: string;

    /**
     * Unread는 읽지 않은 메일 여부(수신 시).
     */
    "unread"?: boolean;

    /**
     * Attachments는 첨부파일 목록(전송 시 로컬 파일 경로, 수신 시 파일명만).
     */
    "attachments"?: Attachment[] | null;
}
