// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./types/models.js";

/**
 * BoardView는 보드 화면에 필요한 데이터를 묶는다.
 */
export interface BoardView {
    "board": types$0.Board;
    "columns": types$0.Column[] | null;
    "cards": types$0.Card[] | null;
}
