// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service는 Wails를 통해 프론트엔드에 노출되는 칸반 서비스다.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./types/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ArchivedCardList는 보드의 아카이브 카드만 반환한다.
 */
export function ArchivedCardList(boardID: string): $CancellablePromise<types$0.Card[] | null> {
    return $Call.ByID(524603361, boardID);
}

/**
 * BoardCreate는 기본 컬럼(할 일, 진행 중, 완료)을 포함한 보드를 만든다.
 */
export function BoardCreate(name: string): $CancellablePromise<types$0.Board | null> {
    return $Call.ByID(3557120955, name);
}

/**
 * BoardDelete는 보드와 그 하위 컬럼·카드를 함께 삭제한다.
 */
export function BoardDelete(id: string): $CancellablePromise<void> {
    return $Call.ByID(1424258008, id);
}

/**
 * BoardGet은 보드와 그 보드에 속한 컬럼·카드를 함께 반환한다.
 */
export function BoardGet(id: string): $CancellablePromise<$models.BoardView | null> {
    return $Call.ByID(3555469669, id);
}

/**
 * BoardList는 보드 목록을 생성 순서로 반환한다.
 */
export function BoardList(): $CancellablePromise<types$0.Board[] | null> {
    return $Call.ByID(311125811);
}

/**
 * BoardUpdate는 보드 이름을 변경한다.
 */
export function BoardUpdate(board: types$0.Board): $CancellablePromise<void> {
    return $Call.ByID(74924202, board);
}

/**
 * CardArchive는 카드를 일반 보드에서 숨긴다.
 */
export function CardArchive(id: string): $CancellablePromise<void> {
    return $Call.ByID(4143791855, id);
}

/**
 * CardDelete는 카드를 영구 삭제한다. 일반 화면에서는 아카이브를 사용한다.
 */
export function CardDelete(id: string): $CancellablePromise<void> {
    return $Call.ByID(3046173052, id);
}

/**
 * CardList는 보드의 활성 카드만 반환한다.
 */
export function CardList(boardID: string): $CancellablePromise<types$0.Card[] | null> {
    return $Call.ByID(3467658471, boardID);
}

/**
 * CardMove는 카드를 지정 컬럼의 지정 위치로 이동하고,
 * 이동 전·후 컬럼의 나머지 카드 순번도 연속된 값으로 다시 정렬한다.
 */
export function CardMove(id: string, columnID: string, position: number): $CancellablePromise<void> {
    return $Call.ByID(2220689206, id, columnID, position);
}

/**
 * CardRestore는 아카이브 카드를 보드에 다시 표시한다.
 */
export function CardRestore(id: string): $CancellablePromise<void> {
    return $Call.ByID(268660551, id);
}

/**
 * CardSave는 신규 카드와 기존 카드의 공통 저장 메서드다.
 */
export function CardSave(card: types$0.Card): $CancellablePromise<types$0.Card | null> {
    return $Call.ByID(3923419722, card);
}

/**
 * ColumnCreate는 보드의 마지막에 컬럼을 추가한다.
 */
export function ColumnCreate(column: types$0.Column): $CancellablePromise<types$0.Column | null> {
    return $Call.ByID(2341723151, column);
}

/**
 * ColumnDelete는 카드가 남아 있지 않은 컬럼만 삭제한다.
 */
export function ColumnDelete(id: string): $CancellablePromise<void> {
    return $Call.ByID(4134599124, id);
}

/**
 * ColumnMove는 같은 보드 안에서 컬럼을 지정 위치로 이동하고 순번을 정규화한다.
 */
export function ColumnMove(id: string, position: number): $CancellablePromise<void> {
    return $Call.ByID(4177607230, id, position);
}

/**
 * ColumnUpdate는 컬럼 이름과 순서를 변경한다.
 */
export function ColumnUpdate(column: types$0.Column): $CancellablePromise<void> {
    return $Call.ByID(646447094, column);
}

/**
 * DueEvents는 마감일이 있는 활성 카드만 캘린더 표시용으로 반환한다.
 */
export function DueEvents(): $CancellablePromise<types$0.DueEvent[] | null> {
    return $Call.ByID(3499600148);
}
