// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service는 프론트엔드에 바인딩되는 문서 모듈 서비스이다.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./types/models.js";

/**
 * Backlinks는 이 문서를 링크하고 있는 문서를 최근 수정순으로 반환한다.
 */
export function Backlinks(id: string): $CancellablePromise<types$0.Document[] | null> {
    return $Call.ByID(3254666885, id);
}

/**
 * Create는 새 문서를 만든다.
 * 같은 제목이 이미 있으면 뒤에 번호를 붙여 유일한 제목으로 저장한다.
 * folderID를 주면 그 폴더 안에 만들고, 비워 두면 폴더 밖에 만든다.
 * 없는 문서로 향하는 링크를 눌렀을 때도 이 메서드로 문서를 만든다.
 */
export function Create(title: string, folderID: string, docType: types$0.DocType): $CancellablePromise<types$0.Document | null> {
    return $Call.ByID(3950882971, title, folderID, docType);
}

/**
 * CreateFolder는 새 폴더를 만든다. parentID를 주면 그 폴더 안에 만든다.
 * 같은 상위 폴더에 이름이 겹치면 뒤에 번호를 붙인다.
 */
export function CreateFolder(name: string, parentID: string): $CancellablePromise<types$0.Folder | null> {
    return $Call.ByID(3592454879, name, parentID);
}

/**
 * Delete는 문서를 삭제한다.
 * 다른 문서의 링크는 그대로 두어, 다시 만들면 링크가 되살아난다.
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(2984808120, id);
}

/**
 * DeleteFolder는 폴더를 지운다.
 * 안에 있던 하위 폴더와 문서는 함께 지우지 않고 한 단계 위로 끌어올린다.
 */
export function DeleteFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(3995033660, id);
}

/**
 * Export는 문서 내용을 지정한 파일 경로에 쓴다.
 * 문서는 존재해야 하며, 본문은 마크다운 원문 그대로 저장한다.
 */
export function Export(path: string, doc: types$0.Document | null): $CancellablePromise<void> {
    return $Call.ByID(334758145, path, doc);
}

/**
 * FindByTitle은 제목으로 문서를 찾는다. 대소문자는 무시하며, 없으면 nil을 반환한다.
 */
export function FindByTitle(title: string): $CancellablePromise<types$0.Document | null> {
    return $Call.ByID(2713743241, title);
}

/**
 * Folders는 사이드바에 보여 줄 순서대로 모든 폴더를 반환한다.
 * 상위 폴더별로 나누기 전에 전체를 한 번 정렬해 두면, 프론트엔드가 상위
 * 폴더로 걸러도 형제끼리의 순서가 그대로 유지된다.
 */
export function Folders(): $CancellablePromise<types$0.Folder[] | null> {
    return $Call.ByID(957327732);
}

/**
 * Get은 ID로 문서를 조회한다.
 */
export function Get(id: string): $CancellablePromise<types$0.Document | null> {
    return $Call.ByID(2903912901, id);
}

/**
 * Import는 외부 파일을 읽어 새 문서로 만든다.
 * 제목은 파일 이름(확장자 제외)으로 하고, 본문은 파일 내용 그대로 담는다.
 * folderID를 주면 그 폴더 안에 만들고, 비워 두면 폴더 밖에 만든다.
 * 같은 제목이 이미 있으면 뒤에 번호를 붙여 유일한 제목으로 만든다.
 */
export function Import(path: string, folderID: string): $CancellablePromise<types$0.Document | null> {
    return $Call.ByID(84518258, path, folderID);
}

/**
 * ImportPaths는 외부 파일 여러 개를 한꺼번에 가져와 새 문서로 만든다.
 * 파일을 창에 끌어다 놓았을 때 백엔드가 받은 경로 목록을 처리하는 데 쓴다.
 * 폴더 지정 없이 최상위로 만들고, 하나라도 실패하면 그 시점에 멈춘다.
 */
export function ImportPaths(paths: string[] | null): $CancellablePromise<types$0.Document[] | null> {
    return $Call.ByID(3133077798, paths);
}

/**
 * List는 사이드바에 보여 줄 순서대로 모든 문서를 반환한다.
 * 순서를 바꾼 적이 없으면 Order가 모두 0이라 최근 수정순이 그대로 유지된다.
 * 프론트엔드가 링크 대상이 존재하는지 판단하려면 제목 전체가 필요하므로
 * 목록에도 본문을 함께 담아 보낸다.
 */
export function List(): $CancellablePromise<types$0.Document[] | null> {
    return $Call.ByID(2411030547);
}

/**
 * MoveDocument는 문서를 다른 폴더의 원하는 자리로 옮긴다.
 * folderID가 비면 폴더 밖으로 빼고, index는 그 폴더 안에서 몇 번째에 둘지다.
 * 옮기기는 내용 변경이 아니므로 마지막 수정 시각은 건드리지 않는다.
 */
export function MoveDocument(id: string, folderID: string, index: number): $CancellablePromise<types$0.Document | null> {
    return $Call.ByID(488859023, id, folderID, index);
}

/**
 * MoveFolder는 폴더를 다른 상위 폴더의 원하는 자리로 옮긴다.
 * 자기 자신이나 자기 하위 폴더 안으로는 옮길 수 없다.
 */
export function MoveFolder(id: string, parentID: string, index: number): $CancellablePromise<types$0.Folder | null> {
    return $Call.ByID(2169345850, id, parentID, index);
}

/**
 * RenameFolder는 폴더 이름을 바꾼다.
 */
export function RenameFolder(id: string, name: string): $CancellablePromise<types$0.Folder | null> {
    return $Call.ByID(3846667425, id, name);
}

/**
 * Save는 문서의 제목과 본문을 저장한다.
 * 제목이 바뀌면 다른 문서의 [[예전 제목]] 링크도 새 제목으로 함께 고친다.
 */
export function Save(doc: types$0.Document | null): $CancellablePromise<types$0.Document | null> {
    return $Call.ByID(3739311142, doc);
}

/**
 * SetType은 문서를 여는 편집기 형식을 바꾼다.
 * 본문은 그대로 두므로 마지막 수정 시각도 바꾸지 않는다.
 */
export function SetType(id: string, docType: types$0.DocType): $CancellablePromise<types$0.Document | null> {
    return $Call.ByID(2261232017, id, docType);
}
