// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service는 프론트엔드에 바인딩되는 문서 모듈 서비스이다.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./types/models.js";

/**
 * Backlinks는 이 문서를 링크하고 있는 문서를 최근 수정순으로 반환한다.
 */
export function Backlinks(id: string): $CancellablePromise<types$0.Document[] | null> {
    return $Call.ByID(3254666885, id);
}

/**
 * Create는 새 문서를 만든다.
 * 같은 제목이 이미 있으면 뒤에 번호를 붙여 유일한 제목으로 저장한다.
 * 없는 문서로 향하는 링크를 눌렀을 때도 이 메서드로 문서를 만든다.
 */
export function Create(title: string): $CancellablePromise<types$0.Document | null> {
    return $Call.ByID(3950882971, title);
}

/**
 * Delete는 문서를 삭제한다.
 * 다른 문서의 링크는 그대로 두어, 다시 만들면 링크가 되살아난다.
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(2984808120, id);
}

/**
 * FindByTitle은 제목으로 문서를 찾는다. 대소문자는 무시하며, 없으면 nil을 반환한다.
 */
export function FindByTitle(title: string): $CancellablePromise<types$0.Document | null> {
    return $Call.ByID(2713743241, title);
}

/**
 * Get은 ID로 문서를 조회한다.
 */
export function Get(id: string): $CancellablePromise<types$0.Document | null> {
    return $Call.ByID(2903912901, id);
}

/**
 * List는 최근 수정한 순서로 모든 문서를 반환한다.
 * 프론트엔드가 링크 대상이 존재하는지 판단하려면 제목 전체가 필요하므로
 * 목록에도 본문을 함께 담아 보낸다.
 */
export function List(): $CancellablePromise<types$0.Document[] | null> {
    return $Call.ByID(2411030547);
}

/**
 * Save는 문서의 제목과 본문을 저장한다.
 * 제목이 바뀌면 다른 문서의 [[예전 제목]] 링크도 새 제목으로 함께 고친다.
 */
export function Save(doc: types$0.Document | null): $CancellablePromise<types$0.Document | null> {
    return $Call.ByID(3739311142, doc);
}
