// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Provider는 단일 캘린더 서비스 제공자의 메타데이터와
 * CalDAV 서버 URL을 나타낸다.
 */
export interface Provider {
    /**
     * ID는 제공자 식별자(예: "google", "apple").
     */
    "id": string;

    /**
     * Name은 표시 이름(예: "Google Calendar", "Apple iCloud").
     */
    "name": string;

    /**
     * Domains은 이 제공자에 해당하는 이메일/계정 도메인 목록.
     * 사용자 이름 입력 시 자동 감지에 사용된다.
     */
    "domains": string[] | null;

    /**
     * CalDAVURL은 CalDAV 서버 캘린더 홈 URL.
     */
    "caldavUrl": string;

    /**
     * HelpURL은 앱 비밀번호/2단계 인증 설정 도움말 URL.
     */
    "helpUrl"?: string;

    /**
     * Note는 사용자 안내 문구(예: "앱 비밀번호가 필요합니다").
     */
    "note"?: string;
}
