// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service는 프론트엔드에 바인딩되는 캘린더 모듈 서비스이다.
 * 모든 메서드는 Wails를 통해 JS/TS에서 호출 가능하다.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as account$0 from "./account/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$0 from "./provider/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./types/models.js";

/**
 * AccountCreate는 새 계정을 등록하고 자격증명을 키체인에 저장한다.
 * id는 자동 생성되어 반환된다. CalDAV 계정은 credential(비밀번호/토큰)이 필수.
 * 로컬 계정(SourceLocal)은 credential을 사용하지 않는다.
 */
export function AccountCreate(acc: account$0.Account | null, credential: string): $CancellablePromise<string> {
    return $Call.ByID(1731330621, acc, credential);
}

/**
 * AccountDelete는 계정과 키체인 자격증명, 로컬 일정을 함께 삭제한다.
 */
export function AccountDelete(id: string): $CancellablePromise<void> {
    return $Call.ByID(2863879722, id);
}

/**
 * AccountGet은 ID로 계정을 조회한다.
 */
export function AccountGet(id: string): $CancellablePromise<account$0.Account | null> {
    return $Call.ByID(129092279, id);
}

/**
 * AccountList는 등록된 모든 캘린더 계정을 반환한다(자격증명 제외).
 */
export function AccountList(): $CancellablePromise<account$0.Account[] | null> {
    return $Call.ByID(2045930849);
}

/**
 * AccountUpdate는 기존 계정 메타데이터를 갱신한다.
 * credential이 빈 문자열이 아니면 키체인 자격증명도 함께 갱신하고,
 * 빈 문자열이면 기존 자격증명을 유지한다.
 */
export function AccountUpdate(acc: account$0.Account | null, credential: string): $CancellablePromise<void> {
    return $Call.ByID(3666554708, acc, credential);
}

/**
 * Calendars는 CalDAV 계정의 캘린더(폴더) 목록을 반환한다.
 * 로컬 계정인 경우 기본 캘린더 하나를 반환한다.
 */
export function Calendars(accID: string): $CancellablePromise<types$0.CalendarInfo[] | null> {
    return $Call.ByID(3429496301, accID);
}

/**
 * EventCreate은 새 일정을 생성한다.
 * 로컬 계정은 저장소에 저장하고, CalDAV 계정은 서버에 PUT 한다.
 */
export function EventCreate(ev: types$0.Event | null): $CancellablePromise<types$0.Event | null> {
    return $Call.ByID(665461826, ev);
}

/**
 * EventDelete는 일정을 삭제한다.
 */
export function EventDelete(calendarID: string, uid: string): $CancellablePromise<void> {
    return $Call.ByID(4656161, calendarID, uid);
}

/**
 * EventList는 접근 가능한 모든 일정을 반환한다.
 * 로컬 계정의 일정은 저장소에서 조회하고,
 * CalDAV 계정의 일정은 서버에서 조회해 합친다.
 * from/to가 빈 문자열이면 전체 범위를 조회한다.
 */
export function EventList($from: string, to: string): $CancellablePromise<types$0.Event[] | null> {
    return $Call.ByID(423387250, $from, to);
}

/**
 * EventUpdate는 기존 일정을 갱신한다.
 * CalDAV 계정은 ETag 기반 동시성 제어를 수행한다.
 */
export function EventUpdate(ev: types$0.Event | null): $CancellablePromise<types$0.Event | null> {
    return $Call.ByID(68121231, ev);
}

/**
 * EventsByAccount는 단일 계정의 일정만 반환한다.
 * CalDAV 계정은 서버에서, 로컬 계정은 저장소에서 조회한다.
 */
export function EventsByAccount(accID: string): $CancellablePromise<types$0.Event[] | null> {
    return $Call.ByID(760386085, accID);
}

/**
 * ProviderList는 사전 정의된 캘린더 서비스 제공자 목록을 반환한다.
 * 프론트엔드에서 계정 추가 시 드롭다운으로 표시하거나,
 * 계정 도메인 자동 인식에 사용한다.
 */
export function ProviderList(): $CancellablePromise<provider$0.Provider[] | null> {
    return $Call.ByID(3362746703);
}

/**
 * ProviderLookupByEmail은 이메일 주소의 도메인으로 제공자를 찾는다.
 * 일치하는 사전 정의 제공자가 없으면 nil을 반환한다.
 * 프론트엔드에서 사용자 이름 입력 중 CalDAV URL 자동 채우기에 사용한다.
 */
export function ProviderLookupByEmail(email: string): $CancellablePromise<provider$0.Provider | null> {
    return $Call.ByID(3661136536, email);
}

/**
 * SyncNow는 CalDAV 계정의 일정을 즉시 동기화한다.
 * 동기화 성공 시 계정의 LastSyncAt을 갱신한다.
 */
export function SyncNow(accID: string): $CancellablePromise<void> {
    return $Call.ByID(1322583891, accID);
}
