// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service는 프론트엔드에 바인딩되는 캘린더 모듈 서비스이다.
 * 모든 메서드는 Wails를 통해 JS/TS에서 호출 가능하다.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../account/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$1 from "./types/models.js";

/**
 * AccountGet은 ID로 계정을 조회한다.
 */
export function AccountGet(id: string): $CancellablePromise<types$0.Account | null> {
    return $Call.ByID(129092279, id);
}

/**
 * AccountList는 캘린더 기능이 켜진 계정만 반환한다(자격증명 제외).
 * 계정 등록·수정·삭제와 Google 재인증은 통합 계정 모듈이 담당한다.
 */
export function AccountList(): $CancellablePromise<types$0.Account[] | null> {
    return $Call.ByID(2045930849);
}

/**
 * Calendars는 CalDAV 계정의 캘린더(폴더) 목록을 반환한다.
 * 로컬 계정인 경우 기본 캘린더 하나를 반환한다.
 */
export function Calendars(accID: string): $CancellablePromise<types$1.CalendarInfo[] | null> {
    return $Call.ByID(3429496301, accID);
}

/**
 * EventCreate은 새 일정을 생성한다.
 * 로컬 계정은 저장소에 저장하고, CalDAV 계정은 서버에 PUT 한다.
 */
export function EventCreate(ev: types$1.Event | null): $CancellablePromise<types$1.Event | null> {
    return $Call.ByID(665461826, ev);
}

/**
 * EventDelete는 일정을 삭제한다.
 */
export function EventDelete(calendarID: string, uid: string): $CancellablePromise<void> {
    return $Call.ByID(4656161, calendarID, uid);
}

/**
 * EventList는 SQLite에 캐시된 접근 가능한 모든 일정을 반환한다.
 * 외부 서버 호출은 SyncNow에서만 수행한다. 화면 진입/월 이동은
 * 네트워크를 사용하지 않고 마지막 동기화 스냅샷을 보여준다.
 * from/to가 빈 문자열이면 전체 범위를 조회한다.
 */
export function EventList($from: string, to: string): $CancellablePromise<types$1.Event[] | null> {
    return $Call.ByID(423387250, $from, to);
}

/**
 * EventUpdate는 기존 일정을 갱신한다.
 * CalDAV 계정은 ETag 기반 동시성 제어를 수행한다.
 */
export function EventUpdate(ev: types$1.Event | null): $CancellablePromise<types$1.Event | null> {
    return $Call.ByID(68121231, ev);
}

/**
 * EventsByAccount는 단일 계정의 일정만 반환한다.
 * CalDAV 계정은 서버에서, 로컬 계정은 저장소에서 조회한다.
 */
export function EventsByAccount(accID: string): $CancellablePromise<types$1.Event[] | null> {
    return $Call.ByID(760386085, accID);
}

/**
 * SyncNow는 CalDAV 계정의 일정을 즉시 동기화한다.
 * 동기화 성공 시 계정의 LastSyncAt을 갱신한다.
 */
export function SyncNow(accID: string): $CancellablePromise<void> {
    return $Call.ByID(1322583891, accID);
}
