// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service는 프론트엔드에 바인딩되는 이메일 모듈 서비스이다.
 * 모든 메서드는 Wails를 통해 JS/TS에서 호출 가능하다.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as account$0 from "./account/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$0 from "./provider/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./types/models.js";

/**
 * AccountCreate는 새 계정을 등록하고 자격증명을 키체인에 저장한다.
 * id는 자동 생성되어 반환된다. credential은 빈 문자열이면 안 된다.
 */
export function AccountCreate(acc: account$0.Account | null, credential: string): $CancellablePromise<string> {
    return $Call.ByID(3332929661, acc, credential);
}

/**
 * AccountDelete는 계정과 키체인 자격증명을 함께 삭제한다.
 * 메타데이터가 이미 없더라도 키체인 잔여물은 제거를 시도한다.
 */
export function AccountDelete(id: string): $CancellablePromise<void> {
    return $Call.ByID(2234678890, id);
}

/**
 * AccountGet은 ID로 계정을 조회한다.
 */
export function AccountGet(id: string): $CancellablePromise<account$0.Account | null> {
    return $Call.ByID(4147542775, id);
}

/**
 * AccountList는 등록된 모든 계정을 반환한다(자격증명 제외).
 */
export function AccountList(): $CancellablePromise<account$0.Account[] | null> {
    return $Call.ByID(1205119905);
}

/**
 * AccountUpdate는 기존 계정 메타데이터를 갱신한다.
 * credential이 빈 문자열이 아니면 키체인 자격증명도 함께 갱신하고,
 * 빈 문자열이면 기존 자격증명을 유지한다.
 */
export function AccountUpdate(acc: account$0.Account | null, credential: string): $CancellablePromise<void> {
    return $Call.ByID(2612896404, acc, credential);
}

/**
 * Folders는 지정한 계정의 IMAP 폴더 목록을 반환한다.
 */
export function Folders(accID: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2640218643, accID);
}

/**
 * List는 지정한 폴더의 최신 메시지를 조회한다.
 * folder가 빈 문자열이면 INBOX를 사용한다.
 */
export function List(accID: string, folder: string): $CancellablePromise<types$0.Message[] | null> {
    return $Call.ByID(1288993830, accID, folder);
}

/**
 * ProviderList는 사전 정의된 이메일 제공자 목록을 반환한다.
 * 프론트엔드에서 계정 추가 시 드롭다운으로 표시하거나,
 * 이메일 도메인 자동 인식에 사용한다.
 */
export function ProviderList(): $CancellablePromise<provider$0.Provider[] | null> {
    return $Call.ByID(2481272719);
}

/**
 * ProviderLookupByEmail은 이메일 주소의 도메인으로 제공자를 찾는다.
 * 일치하는 사전 정의 제공자가 없으면 nil을 반환한다.
 * 프론트엔드에서 이메일 입력 중 서버 필드 자동 채우기에 사용한다.
 */
export function ProviderLookupByEmail(email: string): $CancellablePromise<provider$0.Provider | null> {
    return $Call.ByID(874965208, email);
}

/**
 * Send는 지정한 계정으로 메일을 발송한다.
 * accID로 계정을 조회하고, 키체인에서 자격증명을 꺼내 SMTP 전송에 사용한다.
 */
export function Send(accID: string, msg: types$0.Message | null): $CancellablePromise<void> {
    return $Call.ByID(3861516648, accID, msg);
}
