// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service는 프론트엔드에 바인딩되는 이메일 모듈 서비스이다.
 * 모든 메서드는 Wails를 통해 JS/TS에서 호출 가능하다.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../account/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$1 from "./types/models.js";

/**
 * AccountGet은 ID로 계정을 조회한다.
 */
export function AccountGet(id: string): $CancellablePromise<types$0.Account | null> {
    return $Call.ByID(4147542775, id);
}

/**
 * AccountList는 메일 기능이 켜진 계정만 반환한다(자격증명 제외).
 * 계정 등록·수정·삭제는 통합 계정 모듈이 담당한다.
 */
export function AccountList(): $CancellablePromise<types$0.Account[] | null> {
    return $Call.ByID(1205119905);
}

/**
 * AttachmentData는 원문 MIME 메시지에서 첨부파일 바이트를 추출해 Base64로 반환한다.
 * 프론트엔드는 List 응답에 포함된 원문과 첨부파일 인덱스를 사용하므로,
 * 다운로드나 미리보기 때 메일 서버를 다시 조회하지 않는다.
 */
export function AttachmentData(raw: string, index: number): $CancellablePromise<string> {
    return $Call.ByID(789902975, raw, index);
}

/**
 * Folders는 지정한 계정의 IMAP 폴더 목록을 반환한다.
 */
export function Folders(accID: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2640218643, accID);
}

/**
 * List는 네트워크를 호출하지 않고 SQLite 캐시에서 목록과 본문을 읽는다.
 */
export function List(accID: string, folder: string): $CancellablePromise<types$1.Message[] | null> {
    return $Call.ByID(1288993830, accID, folder);
}

/**
 * ListMore는 현재 캐시에 서버의 다음 페이지를 추가하고 중복 메시지는 제거한다.
 */
export function ListMore(accID: string, folder: string, pageToken: string): $CancellablePromise<types$1.MessagePage> {
    return $Call.ByID(3413442055, accID, folder, pageToken);
}

/**
 * ListRefresh는 사용자가 명시적으로 새로고침했을 때만 메일 서버를 조회하고,
 * 반환된 목록과 본문을 SQLite 캐시에 저장한다.
 */
export function ListRefresh(accID: string, folder: string): $CancellablePromise<types$1.Message[] | null> {
    return $Call.ByID(3233957613, accID, folder);
}

/**
 * ListRefreshPage는 서버에서 지정한 페이지를 조회한다.
 * 첫 페이지는 캐시를 교체하고, 이후 페이지는 ListMore가 기존 캐시에 합친다.
 */
export function ListRefreshPage(accID: string, folder: string, pageToken: string): $CancellablePromise<types$1.MessagePage> {
    return $Call.ByID(4200415102, accID, folder, pageToken);
}

/**
 * MessagesDelete는 선택한 메일들을 삭제하고 캐시에서도 제거한다.
 * Gmail 계정은 휴지통으로 이동하고, IMAP 계정은 \Deleted 플래그 후 EXPUNGE로 폴더에서 지운다.
 */
export function MessagesDelete(accID: string, folder: string, refs: types$1.MessageRef[] | null): $CancellablePromise<void> {
    return $Call.ByID(1986850689, accID, folder, refs);
}

/**
 * MessagesMarkRead는 선택한 메일들의 읽음 상태를 한 번에 변경하고 캐시에도 반영한다.
 * Gmail 계정은 UNREAD 라벨을, IMAP 계정은 \Seen 플래그를 사용한다.
 */
export function MessagesMarkRead(accID: string, folder: string, refs: types$1.MessageRef[] | null, read: boolean): $CancellablePromise<void> {
    return $Call.ByID(962410363, accID, folder, refs, read);
}

/**
 * MessagesMove는 선택한 메일들을 다른 폴더로 옮기고 원래 폴더 캐시에서 제거한다.
 * Gmail 계정은 폴더 대신 라벨을 바꾼다. 옮긴 폴더의 캐시는 그 폴더를 새로고침할 때 채워진다.
 */
export function MessagesMove(accID: string, folder: string, targetFolder: string, refs: types$1.MessageRef[] | null): $CancellablePromise<void> {
    return $Call.ByID(3338337171, accID, folder, targetFolder, refs);
}

/**
 * Page는 네트워크를 호출하지 않고 캐시된 목록과 다음 페이지 커서를 반환한다.
 */
export function Page(accID: string, folder: string): $CancellablePromise<types$1.MessagePage> {
    return $Call.ByID(1910736881, accID, folder);
}

/**
 * Send는 지정한 계정으로 메일을 발송한다.
 * accID로 계정을 조회하고, 키체인에서 자격증명을 꺼내 SMTP 전송에 사용한다.
 */
export function Send(accID: string, msg: types$1.Message | null): $CancellablePromise<void> {
    return $Call.ByID(3861516648, accID, msg);
}
