// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as account$0 from "../account/models.js";

/**
 * Provider는 단일 이메일 서비스 제공자의 메타데이터와 서버 설정을 나타낸다.
 */
export interface Provider {
    /**
     * ID는 제공자 식별자(예: "naver", "gmail").
     */
    "id": string;

    /**
     * Name은 표시 이름(예: "Naver Mail", "Gmail").
     */
    "name": string;

    /**
     * Domains은 이 제공자에 해당하는 이메일 도메인 목록.
     * 사용자 이메일 주소의 도메인이 여기에 포함되면 이 제공자로 인식한다.
     */
    "domains": string[] | null;

    /**
     * HelpURL은 앱 비밀번호/2단계 인증 설정 도움말 URL.
     * 사용자에게 안내 링크로 표시한다.
     */
    "helpUrl"?: string;

    /**
     * Note는 사용자 안내 문구(예: "앱 비밀번호가 필요합니다").
     */
    "note"?: string;

    /**
     * SMTP는 발송 서버 설정. nil이면 발송 미지원 제공자.
     */
    "smtp"?: account$0.ServerConfig | null;

    /**
     * IMAP은 수신 서버 설정. nil이면 수신 미지원 제공자.
     */
    "imap"?: account$0.ServerConfig | null;
}
