// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service는 프론트엔드에 바인딩되는 시계 모듈 서비스이다.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./types/models.js";

/**
 * SaveSettings는 설정을 검증해 저장하고, 실제로 저장된 값을 반환한다.
 */
export function SaveSettings(settings: types$0.Settings | null): $CancellablePromise<types$0.Settings | null> {
    return $Call.ByID(2343180660, settings);
}

/**
 * Settings는 저장된 설정을 반환한다. 저장된 값이 없으면 기본값을 준다.
 */
export function Settings(): $CancellablePromise<types$0.Settings | null> {
    return $Call.ByID(1441986833);
}
