// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DocType은 문서를 어떤 편집기로 열지 정한다.
 */
export type DocType = string;

/**
 * Predefined constants for type DocType.
 * @namespace
 */
export const DocType = {
    /**
     * TypeMarkdown은 마크다운 원문을 편집하고 옆에서 미리 보는 형식이다.
     */
    TypeMarkdown: "markdown",

    /**
     * TypeRichText는 서식을 바로 보며 편집하는 WYSIWYG 형식이다.
     */
    TypeRichText: "wysiwyg",

    /**
     * TypePlainText는 서식 없이 원문만 다루는 형식이다.
     */
    TypePlainText: "text",
};

/**
 * Document는 문서 하나이다.
 * 본문에 [[다른 문서 제목]] 형태로 링크를 적으면 문서 사이를 오갈 수 있다.
 */
export interface Document {
    /**
     * ID는 문서 식별자(자동 생성). 제목이 바뀌어도 유지된다.
     */
    "id": string;

    /**
     * Title은 문서 제목이자 링크 대상 이름이다.
     * 링크가 제목으로 문서를 찾으므로 대소문자를 무시하고 유일해야 한다.
     */
    "title": string;

    /**
     * Type은 이 문서를 여는 편집기 형식이다. 문서마다 따로 정한다.
     */
    "type"?: DocType;

    /**
     * FolderID는 문서가 담긴 폴더이다. 비어 있으면 폴더에 넣지 않은 문서다.
     */
    "folderId"?: string;

    /**
     * Content는 본문이다. 형식과 무관하게 마크다운 원문으로 보관한다.
     */
    "content": string;

    /**
     * Links는 본문이 참조하는 다른 문서 제목 목록이다.
     * 저장할 때 본문에서 다시 계산하므로 직접 채워 보낼 필요는 없다.
     */
    "links"?: string[] | null;

    /**
     * CreatedAt은 생성 시각(RFC3339).
     */
    "createdAt"?: string;

    /**
     * UpdatedAt은 마지막 수정 시각(RFC3339).
     */
    "updatedAt"?: string;
}

/**
 * Folder는 문서를 묶는 폴더이다.
 * 폴더 안에 폴더를 두지는 않으며, 문서는 폴더 하나에만 속한다.
 */
export interface Folder {
    /**
     * ID는 폴더 식별자(자동 생성)이다.
     */
    "id": string;

    /**
     * Name은 사이드바에 보이는 폴더 이름이다.
     */
    "name": string;

    /**
     * CreatedAt은 생성 시각(RFC3339)이다.
     */
    "createdAt"?: string;
}
