// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service는 프론트엔드에 바인딩되는 통합 계정 서비스이다.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$0 from "../calendar/provider/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$1 from "../email/provider/models.js";

/**
 * CalendarProviderList는 사전 정의된 캘린더 제공자 목록을 반환한다.
 */
export function CalendarProviderList(): $CancellablePromise<provider$0.Provider[] | null> {
    return $Call.ByID(467452984);
}

/**
 * CalendarProviderLookup은 이메일 도메인으로 CalDAV 서버 설정을 찾는다.
 */
export function CalendarProviderLookup(email: string): $CancellablePromise<provider$0.Provider | null> {
    return $Call.ByID(1662661094, email);
}

/**
 * Create는 새 계정을 등록하고 자격증명을 키체인에 저장한다.
 * 메일과 캘린더 중 최소 하나는 사용하도록 설정해야 한다.
 */
export function Create(acc: types$0.Account | null, credential: string): $CancellablePromise<string> {
    return $Call.ByID(270099931, acc, credential);
}

/**
 * Delete는 계정과 키체인 자격증명을 함께 삭제한다.
 * 해당 계정의 메일 캐시와 일정 캐시는 각 모듈이 계정을 찾지 못하면 사용하지 않는다.
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(2432204280, id);
}

/**
 * Get은 ID로 계정을 조회한다.
 */
export function Get(id: string): $CancellablePromise<types$0.Account | null> {
    return $Call.ByID(2475585797, id);
}

/**
 * GoogleConnect는 Google OAuth 인증을 수행하고 계정을 저장한다.
 * 발급된 토큰 하나를 Gmail과 Google 캘린더가 함께 사용한다.
 */
export function GoogleConnect(acc: types$0.Account | null): $CancellablePromise<string> {
    return $Call.ByID(2565973714, acc);
}

/**
 * GoogleReconnect는 토큰이 만료·철회된 기존 Google 계정을 다시 인증한다.
 * 계정 설정은 그대로 두고 키체인의 토큰만 새로 발급받아 교체하며,
 * 성공하면 메일과 캘린더의 재인증 안내가 함께 해제된다.
 */
export function GoogleReconnect(id: string): $CancellablePromise<void> {
    return $Call.ByID(4016947121, id);
}

/**
 * List는 등록된 모든 계정을 반환한다(자격증명 제외).
 */
export function List(): $CancellablePromise<types$0.Account[] | null> {
    return $Call.ByID(520209235);
}

/**
 * MailProviderList는 사전 정의된 메일 제공자 목록을 반환한다.
 */
export function MailProviderList(): $CancellablePromise<provider$1.Provider[] | null> {
    return $Call.ByID(3774373885);
}

/**
 * MailProviderLookup은 이메일 도메인으로 SMTP/IMAP 서버 설정을 찾는다.
 * 일치하는 사전 정의 제공자가 없으면 nil을 반환한다.
 */
export function MailProviderLookup(email: string): $CancellablePromise<provider$1.Provider | null> {
    return $Call.ByID(2524523799, email);
}

/**
 * Update는 기존 계정을 갱신한다.
 * credential이 빈 문자열이면 키체인의 기존 자격증명을 유지한다.
 */
export function Update(acc: types$0.Account | null, credential: string): $CancellablePromise<void> {
    return $Call.ByID(3889368522, acc, credential);
}
