// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Account는 메일과 캘린더가 공유하는 단일 계정이다.
 * 비밀번호와 OAuth 토큰은 이 구조체에 담기지 않으며 OS 키체인에 별도 보관된다.
 */
export interface Account {
    /**
     * ID는 계정 식별자(자동 생성). 메일 캐시와 일정 캐시의 키로도 쓰이므로 변경되지 않는다.
     */
    "id": string;

    /**
     * Name은 사용자 지정 표시 이름(예: "회사 계정").
     */
    "name": string;

    /**
     * Email은 계정 이메일 주소이자 로그인 아이디.
     */
    "email"?: string;

    /**
     * DisplayName은 발송 메일 From 표시에 사용할 이름.
     */
    "displayName"?: string;

    /**
     * AuthType은 인증 방식 ("password" 또는 "oauth2").
     * OAuth 계정은 토큰 하나로 Gmail과 Google 캘린더를 함께 사용한다.
     */
    "authType"?: AuthType;

    /**
     * Mail은 메일 기능 설정. nil이면 메일 모듈에 노출되지 않는다.
     */
    "mail"?: MailConfig | null;

    /**
     * Calendar는 캘린더 기능 설정. nil이면 캘린더 모듈에 노출되지 않는다.
     */
    "calendar"?: CalendarConfig | null;

    /**
     * AuthError는 재인증이 필요한 마지막 인증 실패 사유이다.
     * 값이 비어 있지 않으면 프론트엔드가 재인증 안내와 버튼을 표시한다.
     */
    "authError"?: string;
}

/**
 * AuthType은 계정 인증 방식이다.
 */
export enum AuthType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * AuthPassword는 비밀번호 또는 앱 비밀번호 인증이다.
     */
    AuthPassword = "password",

    /**
     * AuthOAuth2는 Google OAuth access/refresh token 인증이다.
     */
    AuthOAuth2 = "oauth2",
};

/**
 * CalendarConfig는 계정의 캘린더 기능 설정이다.
 * nil이면 이 계정은 캘린더 모듈에서 사용되지 않는다.
 */
export interface CalendarConfig {
    /**
     * Source는 일정 저장소 종류 ("local" 또는 "caldav").
     */
    "source": CalendarSource;

    /**
     * URL은 CalDAV 서버 캘린더 홈 URL. Source가 "caldav"일 때만 사용된다.
     */
    "url"?: string;

    /**
     * Username은 CalDAV 로그인 사용자 이름.
     * 비어 있으면 계정의 Email을 사용한다.
     */
    "username"?: string;

    /**
     * Color는 캘린더 표시 색상(HEX).
     */
    "color"?: string;

    /**
     * SyncEnabled는 외부 캘린더 동기화 활성화 여부.
     */
    "syncEnabled"?: boolean;

    /**
     * LastSyncAt은 마지막 동기화 시각(RFC3339).
     */
    "lastSyncAt"?: string;
}

/**
 * CalendarSource는 일정 저장소 종류이다.
 */
export enum CalendarSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * CalendarSourceLocal은 외부 서버 없이 앱에만 저장하는 캘린더이다.
     */
    CalendarSourceLocal = "local",

    /**
     * CalendarSourceCalDAV는 외부 CalDAV 서버 연동 캘린더이다.
     */
    CalendarSourceCalDAV = "caldav",
};

/**
 * MailConfig는 계정의 메일 기능 설정이다.
 * nil이면 이 계정은 이메일 모듈에서 사용되지 않는다.
 */
export interface MailConfig {
    /**
     * SMTP는 발송 서버 설정. 비어 있으면 발송 기능 비활성화.
     */
    "smtp"?: ServerConfig | null;

    /**
     * IMAP은 수신 서버 설정. 비어 있으면 수신 기능 비활성화.
     * OAuth 계정은 Gmail API를 사용하므로 비어 있어도 된다.
     */
    "imap"?: ServerConfig | null;
}

/**
 * ServerConfig는 단일 프로토콜의 서버 연결 정보이다.
 */
export interface ServerConfig {
    /**
     * Host는 서버 호스트명.
     */
    "host": string;

    /**
     * Port는 서버 포트.
     */
    "port": number;

    /**
     * Encryption은 암호화 방식 ("none", "starttls", "tls").
     */
    "encryption": string;
}
