// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CalendarInfo는 캘린더(폴더) 메타데이터를 나타낸다.
 * CalDAV 서버의 calendar-home-set 하위 캘린더와
 * 로컬 기본 캘린더 모두 이 형태로 표현된다.
 */
export interface CalendarInfo {
    /**
     * Href는 CalDAV 서버 상의 캘린더 경로.
     */
    "href"?: string;

    /**
     * Name은 캘린더 표시 이름.
     */
    "name": string;

    /**
     * Color는 캘린더 색상(HEX, 예: "#4f7cff").
     */
    "color"?: string;

    /**
     * Description은 캘린더 설명.
     */
    "description"?: string;
}

/**
 * Event는 단일 캘린더 일정을 나타낸다.
 * 로컬 저장소와 외부 CalDAV 서버 양쪽에서 재사용된다.
 */
export interface Event {
    /**
     * UID는 일정 식별자. CalDAV 서버에서는 VEVENT UID와 매핑되고,
     * 로컬 일정은 자동 생성된 고유 문자열을 사용한다.
     */
    "uid": string;

    /**
     * CalendarID는 이 일정이 속한 캘린더(계정)의 ID.
     */
    "calendarId": string;

    /**
     * Title은 일정 제목(요약).
     */
    "title": string;

    /**
     * Description은 상세 설명.
     */
    "description"?: string;

    /**
     * Location은 장소.
     */
    "location"?: string;

    /**
     * Start은 일정 시작 시각(RFC3339).
     */
    "start": string;

    /**
     * End은 일정 종료 시각(RFC3339).
     */
    "end": string;

    /**
     * AllDay가 true면 종일 일정. Start/End는 날짜만 의미한다.
     */
    "allDay"?: boolean;

    /**
     * RecurrenceRule은 반복 규칙(RFC 5545 RRULE 문자열, 예: "FREQ=WEEKLY;BYDAY=MO").
     */
    "recurrenceRule"?: string;

    /**
     * Attendees는 참석자 이메일 목록.
     */
    "attendees"?: string[] | null;

    /**
     * Organizer는 주최자 이메일.
     */
    "organizer"?: string;

    /**
     * ETag는 CalDAV 서버에서 사용하는 동시성 제어용 태그.
     * 로컬 일정은 비어 있다.
     */
    "etag"?: string;

    /**
     * Href는 CalDAV 서버 상의 객체 경로.
     * 로컬 일정은 비어 있다.
     */
    "href"?: string;
}
