// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Board는 칸반 보드 하나를 나타낸다.
 */
export interface Board {
    "id": string;
    "name": string;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * Card는 칸반 보드에서 관리하는 업무를 나타낸다.
 */
export interface Card {
    "id": string;
    "boardId": string;
    "columnId": string;
    "title": string;
    "description"?: string;
    "dueDate"?: string;
    "priority"?: string;
    "labels"?: string[] | null;
    "checklist"?: ChecklistItem[] | null;
    "assignee"?: string;
    "attachments"?: string[] | null;
    "position": number;
    "archived": boolean;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * ChecklistItem은 카드 안의 하위 업무를 나타낸다.
 */
export interface ChecklistItem {
    "id": string;
    "title": string;
    "completed": boolean;
}

/**
 * Column은 보드 안에서 카드의 상태와 순서를 나타낸다.
 */
export interface Column {
    "id": string;
    "boardId": string;
    "name": string;
    "position": number;
    "createdAt": string;
}

/**
 * DueEvent는 캘린더 모듈이 칸반 카드의 마감일을 표시할 때 사용하는 읽기 모델이다.
 */
export interface DueEvent {
    "cardId": string;
    "title": string;
    "dueDate": string;
}
