// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PomodoroSettings는 뽀모도로 한 주기의 길이 설정이다.
 */
export interface PomodoroSettings {
    /**
     * FocusMinutes는 집중 시간(분).
     */
    "focusMinutes": number;

    /**
     * ShortBreakMinutes는 짧은 휴식 시간(분).
     */
    "shortBreakMinutes": number;

    /**
     * LongBreakMinutes는 긴 휴식 시간(분).
     */
    "longBreakMinutes": number;

    /**
     * RoundsBeforeLongBreak는 긴 휴식까지의 집중 횟수.
     */
    "roundsBeforeLongBreak": number;
}

/**
 * Settings는 앱을 다시 켜도 유지해야 하는 시계 모듈 설정이다.
 * 스톱워치와 타이머의 진행 상태는 화면에서만 관리하므로 저장하지 않는다.
 */
export interface Settings {
    /**
     * WorldClocks는 세계 시간에 표시할 IANA 시간대 이름 목록이다(예: "Asia/Tokyo").
     */
    "worldClocks": string[] | null;

    /**
     * Pomodoro는 뽀모도로 길이 설정이다.
     */
    "pomodoro": PomodoroSettings;
}
