// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Account는 등록된 이메일 계정을 나타낸다.
 * 비밀번호/토큰은 이 구조체에 저장되지 않으며 OS 키체인에 별도 보관된다.
 */
export interface Account {
    /**
     * ID는 계정 식별자(자동 생성). 변경되지 않는 안정적 키.
     */
    "id": string;

    /**
     * Name은 사용자 지정 계정 표시 이름(예: "회사 메일").
     */
    "name": string;

    /**
     * Email은 계정 이메일 주소이자 로그인 아이디.
     */
    "email": string;

    /**
     * DisplayName은 발송 메일 From 표시에 사용할 이름.
     */
    "displayName"?: string;

    /**
     * SMTP는 발송 서버 설정. 빈 값이면 발송 기능 비활성화.
     */
    "smtp"?: ServerConfig | null;

    /**
     * IMAP은 수신 서버 설정. 빈 값이면 수신 기능 비활성화.
     */
    "imap"?: ServerConfig | null;

    /**
     * AuthType은 인증 방식 ("password" 또는 "oauth2").
     * 현재 첫 버전은 password만 지원한다.
     */
    "authType"?: string;
}

/**
 * ServerConfig는 단일 프로토콜의 서버 연결 정보를 나타낸다.
 */
export interface ServerConfig {
    /**
     * Host는 서버 호스트명.
     */
    "host": string;

    /**
     * Port는 서버 포트.
     */
    "port": number;

    /**
     * Encryption은 암호화 방식 ("none", "starttls", "tls").
     */
    "encryption": string;
}
